package org.wecancoeit.reviews;

import org.springframework.stereotype.Repository;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

@Repository
public class ReviewRepository {

    Map<Long, Review> reviewsList = new HashMap<>();

    public ReviewRepository(){
        Review eastBlueSaga = new Review(1L,"East Blue Saga","This is the first 1st Saga (season) in One Piece. This saga introduces our main protagonist Monkey D. Luffy, a pirate who ate the Gomu Gomu no Mi fruit which turns him into a rubber man. It is also the beginning of his journey of finding the One Piece (the ultimate treasure) and becoming the Pirate King. There are 8 arcs (parts or chapters) in the East Blue Saga that add up to a total of 61 episodes (including filler episodes that don't follow the main storyline.). Throughout the episodes, we watch our main protagonist go on adventures and recruit 4 new crewmates: Zoro the swordsman, Sanji the cook, Usopp the sniper, and Nami the navigator, while fighting off both Pirates and Marines. This Saga is fun the watch and is comical since the characters are very goofy and Luffy somehow always finds trouble. The only downside to this Saga is that it can seem very slow since Luffy is searching for his crew, so there's not much excitement and interesting fights till he finds the first 3 crewmates. Overall I would rate this Saga a 7 out of 10 cause despite the lack of action, it does introduce a lot of unique characters that make you laugh, and the Arlong Park Arc(7th arc) really picks up the story in terms of introducing strong antagonist and searching for the One Piece.", "https://images-na.ssl-images-amazon.com/images/I/91wUZYKH0JL.jpg" );
        Review alabastaSaga = new Review(2L,"Alabasta Saga","This is the 2nd Saga in One Piece. This Saga is made up of 7 arcs in a total of 73 episodes and introduces the Strawhats (Luffy's pirate crew name) new crewmates: Chopper, who is a talking reindeer who also happens to be a doctor, and Robin, an archeologist. The Alabasta Saga is where the Strawhats start their journey in searching for the One Piece and this is where the show absolutely hooks the fans. The islands where the Strawhats travel to become more unique in terms of design and personality. In this saga, Luffy and the crew run into a princess name Vivi, who then asked the Strawhats to help take her country back since it's been conquered by Crocodile, one of the 7 warlords of the sea (powerful pirates under the marines protection). Crocodile is the antagonist of this saga and he is a mafia type character who ate the Suna Suna no Mi fruit, which allows him to control sand while being made out of sand. The Strawhats then agree to help the princess and partake in a war to retake Alabasta. This Saga is considered perfect in my opinion because the adventure is very entertaining with the unique islands and the many characters who are surprisingly unique in personality. This saga also has entertaining fights between the Strawhats and the enemies they face. Overall I would give this Saga a 8 out of 10.", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1572271551l/6406094._SY475_.jpg");
        Review skyIslandSaga = new Review(3L, "Sky Island Saga","This is the 3rd Saga in One Piece. This Saga is made up of 5 arcs(3 of the arcs being filler) in a total of 70 episodes. In this Saga, the Strawhats' travel to Sky Island, which if you didn't guess by the name, it's an island in the sky. It then introduces the poneglyphs, which are giant indestructible cubes with an ancient language written on them. The poneglyphs supposedly have clues written on them to help find the One Piece, but there are only a few people in the world that can actually read this language with Robin being one of those few. While on Sky Island, the crew runs into the antagonist Enel. Enel is a self-proclaimed god that ate the Goro Goro no Mi fruit, which allows him to generate lightning while being made out of it. Compared to Alabasta this arc may seem slow since it's less action-packed and more educational about the One Piece. The adventure is more comical and laid back until they meet Enel. Overall I would rate this saga a 6 out of 10 since it's slow and laid back, but it is still enjoyable with all the jokes, the island design, and Enel being one of the cooler antagonists.", "https://m.media-amazon.com/images/I/61yNgSJ0HvL.jpg");
        Review water7Saga = new Review(4L,"Water 7 Saga", "This is the 4th Saga in One Piece. This Saga is made up of 7 arcs (3 filler) with a total of 118 episodes. In this Saga, the Strawhats' travel to an island home to shipwrights called Water 7. While they're at Water 7 they gain a new crewmate named Franky who becomes their shipwright. They also run into a group of secret marines called CP9 who kidnap one of their members. The crew then goes to a marine base called Eneis Lobby to declare war against the World Government to save their crewmate. This Saga is one of the best ones because it has a good balance of action and adventure. It also introduces many important characters that play a major part in the One Piece story. Water 7 also has an incredible design. Overall I would rate this Saga 8 out of 10.", "https://www.rightstufanime.com/images/productImages/9781421534596_manga-One-Piece-Graphic-Novel-43-Water-Seven-primary.jpg");
        Review thrillerBarkSaga = new Review(5L, "Thriller Bark Saga", "This is the 5th Saga in One Piece. This Saga is made up of 4 arcs (3 filler) with a total of 58 episodes. It also introduces the Strawhats' new crewmate: Brook, a skeleton that is a musician. In this saga, the Strawhats run into a ship full of monsters that's the size of an island called Thriller Bark. The ship is owned by one of the 7 Warlords of the sea, Gecko Moira who ate the Kage Kage no Mi fruit, which gives him the ability to manifest and control shadows as physical entities. Luffy being the adventurer that he is decides that the crew should explore thriller bark where they run into and fight Gecko Moira. This Saga is a bit like Sky Island where it is more comical than action-packed, but Overall I would give it a 7 out of 10.", "https://static.tvtropes.org/pmwiki/pub/images/screen_shot_2018_05_11_at_64315_pm.png");
        Review summitWarSaga = new Review(6L, "Summit War Saga", "The 6th and the last saga of the 1st half or pre-timeskip in One Piece. This Saga is made up of 8 arcs (2 filler) with a total of 131 episodes. This Saga is where the story of One Piece becomes more intense and serious for the Strawhats. It starts with the Strawhats traveling to Sabaody Archipelago: an island known for hosting a slave trading ring for the World Nobles and the gateway to the New World(the other half of the world). The Strawhats then stirred up trouble and got separated, leading to Luffy being imprisoned at Impel Down: the strongest prison in the World. Luffy being the trouble maker that he is, wounds up breaking out of Impel Down to save his brother Ace (a notorious pirate) from being executed at the marine headquarters called Marineford. He then arrives at Marineford and joins one of the 4 emperors of the sea (4 of the strongest pirates in the world): Whitebeard to save his brother. This rescue turned into a war between the Whitebeard Pirates and the World Government. This Saga introduces a large number of new characters while bringing back some of the old ones and even though it has become more serious, it still has a mix of comedy to ease up on the constant tension. Overall this is one of the top 3 best Sagas in One Piece scoring a perfect 10 out of 10.", "https://pm1.narvii.com/6316/01cc3ee4f0ea6c8cb153a1903783e8c01cade945_hq.jpg");
        Review fishManIslandSaga= new Review(7L, "Fish-Man Island Saga", "This is the 7th and the beginning of the 2nd half or post-timeskip in One Piece. This saga has 3 arcs (1 of them being a special crossover) consisting of 57 episodes. In this saga, the Strawhat crew reunites after 2 years of training separately. Once they reunited and caused trouble at Sabaody of course, they begin their journey to the new world by traveling to the underwater island called Fish-Man Island. This saga was refreshing to watch since there was a break in the show. The character designs were also updated and were really nice. Fish-Man Island was also hilarious with the crew antics and it always displayed the growth the characters made in terms of maturity and skills. The antagonist Hordy Jones was an interesting character, but in terms of his power and strength, he didn't seem as strong or cool as the other characters. They also introduced Big Mom (One of the 4 Emperors) and Luffy's first interaction with her which built up a lot of excitement. Overall I would give this Saga a 7 out of 10 since the development of the Strawhats and the excitement Oda built for the next Saga was awesome. Hordy Jones was just a bit disappointing in terms of antagonist.", "https://m.media-amazon.com/images/I/61wnW0yelSL.jpg");
        Review dressrosaSaga = new Review(8L, "Dressrosa Saga", "The 8th Saga in One Piece that has 5 arcs (3 fillers) that consist of 171 episodes. The Stawhats begin this saga by traveling to an Island that's half Volcanic with Lava everywhere and half-frozen. The Island was called Punk Hazard where the Strawhats meet unusual characters named Kin'emon and Momonosuke who ask them to help save their country. Punk Hazard is also where they run into old characters such as Smoker (marine) and Law (pirate) who also proposed an alliance to take down the 4 Emperors of the Sea. After dealing with Cesar a mad scientist (antagonist) at Punk Hazard, the Strawhats travel to Dressrosa to start their plan of taking down the Emperors. Dressrosa was a Spanish themed island where half the citizens were toys. Dressrosa was also conquered by another warlord of the sea named Doflamingo that was creating and dealing artificial fruit. In our world Doflamingo would be considered a cartel leader. Overall I would give this Saga an 8 out of 10. It was really comical and it was nice to see some of the old characters rejoin the show. Doflamingo was by far one of my favorite antagonists since everything about him was evil and ruthless including his laugh. The new characters were also unique as usual, but they were more interesting and weird(in a good way) than any of the past characters.", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1461521505l/27406771.jpg");
        Review fourEmperorsSaga = new Review(9L, "Four Emperors Saga", "This is the 8th and current Saga with 8 arcs (4 filler arcs) and 278+ episodes, making it the longest saga. This saga is by far the best saga in the entirety of the show scoring a perfect 10 out of 10 for me. It starts off with the Strawhats finding more allies to fight against Kaido (One of the Emperors), who took over Momonosuke's country. Then Luffy and part of the Strawhats head to Whole Cake Island which is home to Big Mom (another emperor) to rescue one of the Strawhats. After escaping Big Mom, Luffy and his crew then head to the land of Wano (Kaido's territory, Momonosuke's country) to rejoin his allies and start the plan to retake Wano. Wano is the craziest arc as of date because not only is there a war between Kaido's Animal Kingdom group and the Strawhats, but other pirate groups, marines, and even another emperor have joined the war for Wano. There is still more to come and I am excited to see what Oda has in store for us fans.", "https://images-na.ssl-images-amazon.com/images/I/91l7+T8cVDL.jpg");

        reviewsList.put(eastBlueSaga.getId(), eastBlueSaga);
        reviewsList.put(alabastaSaga.getId(), alabastaSaga);
        reviewsList.put(skyIslandSaga.getId(), skyIslandSaga);
        reviewsList.put(water7Saga.getId(), water7Saga);
        reviewsList.put(thrillerBarkSaga.getId(), thrillerBarkSaga);
        reviewsList.put(summitWarSaga.getId(), summitWarSaga);
        reviewsList.put(fishManIslandSaga.getId(), fishManIslandSaga);
        reviewsList.put(dressrosaSaga.getId(), dressrosaSaga);
        reviewsList.put(fourEmperorsSaga.getId(), fourEmperorsSaga);

    }

    public ReviewRepository(Review ...reviewsToAdd){
        for(Review review: reviewsToAdd){
            reviewsList.put(review.getId(), review);
        }
    }

    public Review findOne(long id) {
        return reviewsList.get(id);
    }

    public Collection<Review> findAll() {
        return reviewsList.values();
    }
}
